### ISSUE TITLE
frame_id query param is not defined

### ISSUE THREAD

**Issue by Kripteks** [discord/embedded-app-sdk#100]
https://discord.com/developers/docs/activities/building-an-activity#step-1-creating-a-new-app

I followed the domestic instructions but it gives the following error: frame_id query param is not defined

why could it be?

<img width="631" alt="Ekran Resmi 2024-04-05 14 59 55" src="https://github.com/discord/embedded-app-sdk/assets/12412907/30affd62-ce76-4286-98de-2c4ee694ec29">

**Comment by Ford2003** [comment]
This is normally when you are at the point of needing to use the activity on discord and you're not really meant to use the website your hosting anymore. Try using the activity on discord website.

**Comment by Kripteks** [comment]
I don't quite understand, I'm already using discord? Do you mean opening the page from discord?

**Comment by Ford2003** [comment]
In the example after some point you no longer go on the website you are hosting and instead you can now access the activity on discord.

**Comment by colinloretz** [comment]
@Ford2003 is correct here. Once you have included the SDK, you should run your activity from within the Discord client. 

There are ways to mock/run your activity outside of Discord which we'll be documenting more soon.
