### ISSUE TITLE
Suggestion: Discord / EAS should fire an event for when the Activity is closing

### ISSUE THREAD

**Issue by peabnuts123** [discord/embedded-app-sdk#101]
Hello all. I have been enjoying integrating the Embedded App SDK (EAS) into my multiplayer game, however I have run into a pretty sticky problem: **I have no way of detecting when a user leaves the activity**. Since my activity is a game, I need to gracefully exit the lobby so that I can remove the player from the game. Currently, it seems that leaving the activity abruptly closes the iframe / webview that the app is running in, which looks like a dropped connection to my server (i.e. the player is marked as "disconnected" - this would normally occur e.g. if your internet dropped). 

I have tried various workarounds which are somewhat successful, however NONE of them seem to work on iOS. Here's what I've tried:

```javascript

// Add listeners to different events, to see if any of them work on every platform
// At least one seems to work on every platform except iOS 
// (`visibilitychange` seems to be the most reliable)
// NONE of these fire when running an Activity in the iOS Discord client
window.addEventListener('unload', () => hangup('unload'));
window.addEventListener('beforeunload', () => hangup('beforeunload'));
window.addEventListener('pagehide', () => hangup('pagehide'));
document.addEventListener('visibilitychange', () => hangup('visibilitychange'));

function hangup(event) {
  console.log(`[Hangup] Event fired: ${event}`);
  // ... Send a "disconnect" message to server over websocket
}
```

I could refactor the way my API works to simply remove a player any time their connection drops but this is IMO pretty intrusive into my architecture, and completely prohibits the ability to implement any kind of robust networking (such as "timing out" or "disconnecting" if your internet drops momentarily). 

I think the Embedded App SDK should expose an event that is fired when the user leaves the activity. I understand this would require changes to the Discord client itself (to give the activity a moment to handle this event before destroying it), but I think not being able to work around this is a pretty large restriction. 

If you know of any better workarounds that I could try, please let me know. I can provide a reproduction or share my activity with you if-needed. Happy to beta test any changes too. Thanks!

**Comment by FinOCE** [comment]
+1 to this, would love if the client could send an webhook on leave or something like that to be able to detect a disconnect without trusting other clients to all spam the api on participant update or wait for the ws disconnect

**Comment by matthova** [comment]
@peabnuts123 great callout. We're still trying to figure out the best way to handle edge cases like this. The harsh reality is that websites do not always have a clean "exit" moment. For example the entire browser can be closed or the mobile app can be killed. In those scenarios, there's no code that a client SDK could offer to cleanup prior to the activity closing.

Something like a webhook could really be ideal, but we don't offer that at this time.

There are a few holistic options to lean on
- Often netcode has a "closed" event which you can reliably use to know when a user has been disconnected
  - For example, the netcode framework Colyseus has the concept of `onLeave` which is handled by disconnection of a user, rather any events from Discord or the embedded-app-sdk. Example [here](https://github.com/discord/embedded-app-sdk/blob/main/examples/react-colyseus/packages/server/src/rooms/StateHandlerRoom.ts#L30)
- (Per your suggestion) if the connection drops for more than a certain amount of time, consider the user "gone"
- (Not recommended, but some trivia) You could utilize the [ACTIVITY_INSTANCE_PARTICIPANTS_UPDATE](https://discord.com/developers/docs/developer-tools/embedded-app-sdk#activityinstanceparticipantsupdate) event
  - This is a bit messy, as it requires another user to broadcast the event to your server. It works ok if you have netcode which designates a user as the activity "host"

I'm closing this issue, as there's not necessarily a clear path forward for our SDK to offer you. The main suggestion would be to lean on existing netcode solutions

**Comment by peabnuts123** [comment]
@matthova Thanks for the consideration, however I think you may have misunderstood what this issue is about. Those are all appropiate solutions for handling edge-cases (e.g. if the user's phone dies, they abruptly quit Discord, etc.). I don't have any issue with handling those via some kind of "Timing out -> Disconnect after 30 seconds" type logic (this is actually what my game is already doing). 

This issue is about happy-path / graceful, intentional exiting of the application (e.g. leaving the activity, or hanging up the call). The Discord client knows when the user clicks the "Leave" button, and could dispatch an event on the iframe. What is happening at-present is the iframe is destroyed immediately and not enough time is even allowed for any of the "page exited" events to fire, let alone a bespoke event as part of the Embedded App SDK (which would be the ideal).

**Comment by peabnuts123** [comment]
@matthova any comments from yourself?

**Comment by hari01584** [comment]
+1 on the thread, this is very much needed
