### ISSUE TITLE
ERROR: frame_id query param is not defined

### ISSUE THREAD

**Issue by Mee632** [discord/embedded-app-sdk#124]
I followed the Instructions of the official Discord Documantation Getting started with my First Activity but it doesnt work.
[https://discord.com/developers/docs/activities/building-an-activity](url)

When I add this code to the main.js file the Page is blank. When I start the server with just the HTML code it shows the Hello World and everything. In the console of the Developer mode of the page with this code I have to add it throws the error message when it comes to line 8. The error Message is "frame_id query param is not defined". It has to have something to do with the SDK because the DISCORD_CLIENT_ID is set correctly I checked that.  

This is the code I have to Add:
![grafik](https://github.com/discord/embedded-app-sdk/assets/84283522/180bab0b-6f0e-4ffc-b2f1-88a5b4c7d93a)

This is the code where the page works:
![grafik](https://github.com/discord/embedded-app-sdk/assets/84283522/35d673bd-a2b3-4302-ad5c-3a1dc4f521a4)

The SDK is installed correctly so this shoud not be the Problem. And it shoud be Imported correctly.

**Comment by Aom92** [comment]
The guide states that you should REALLY use the cloudflared tunnel, it you do not add it to your URL mappings the app is displayed as a blank page

**Comment by 1j01** [comment]
Another reason this error can be shown is if your app navigates the iframe without preserving the query string.
For example, I found this gem in my code:
```js
// Note: gets rid of query string (?) portion of the URL
// This is desired for upgrading backwards compatibility URLs;
// may not be desired for future cases.
const new_url = `${location.origin}${location.pathname}#${new_hash}`;
```
So I changed it to:
```js
// Note: previously this omitted the query string (`location.search`) portion of the URL
// to support upgrading backwards compatibility URLs, but the query string is needed for the Discord app.
// TODO: fix backwards compatibility URLs? what were they? are they still relevant? probably not...
const new_url = `${location.origin}${location.pathname}${location.search}#${new_hash}`;
```
Some things to search your codebase for:
- `location =`
- `location.href =`
- `location.search =`
- `history.replaceState`
- `history.pushState`
