### ISSUE TITLE
Cross Origin Isolation and SharedArrayBuffer

### ISSUE THREAD

**Issue by krunkske** [discord/embedded-app-sdk#194]
## I don't know if this is the right place to ask/report this so please tell me if I'm in the wrong place.

-  Currently while trying to make an activity, Cross Origin Isolation and SharedArrayBuffer don't seem work at all. I'm using a simple python server that sends the required headers. It works perfectly fine in a browser localhost or trough the Cloudflare proxy.

- I need this due to the Godot Engine (https://github.com/godotengine/godot) requiring it for web exports. SharedArrayBuffer can be disabled if needed in the Godot 4.3 beta but your game will be unable to use multiple cores/treads so it's not ideal.

- If  you would like to check out the code then It's available in this repository : https://github.com/krunkske/battleships-godot/tree/1.1/
![image](https://github.com/discord/embedded-app-sdk/assets/123201489/b99b05d5-a5cd-4a23-a3da-d2b4637530e4)

- Thanks for the help!

**Comment by matthova** [comment]
Correct, unfortunately due to the requirements to enable shared buffer arrays within discord we cannot enable them for activities.

**Comment by aduermael** [comment]
@matthova there's no plan to enable SharedArrayBuffer at some point? Security concerns?
