### ISSUE TITLE
Getting stuck at await .ready()

### ISSUE THREAD

**Issue by Hosfad** [discord/embedded-app-sdk#195]
Hello developers, i have been working on a discord activity (Game) and it has been a great time, i have ran into a small issue : 

Discord embedded sdk getting on the .ready() function.

I have tried to authorize the user through the embedded sdk like this : 

```ts
    const discordSdk = new DiscordSDK(import.meta.env.VITE_CLIENT_ID);
    onMount(async () => {
        console.log("Waiting for discord SDK to be ready");
        await discordSdk.ready();
        console.log("Discord SDK ready");

        const { code } = await discordSdk.commands.authorize({
            client_id: import.meta.env.VITE_CLIENT_ID,
            response_type: "code",
            state: "",
            prompt: "none",
            scope: ["identify", "guilds"],
        });
        ...
    });
```
The issue is that the await discordSdk.ready() promise never resolves, and it never gets to the log after it or any of the code after it.

I have worked around this issue so far by making my own oauth2 flow aka redirecting the user manually and getting the code + making all the manual api https requests to finaly get to the user

and that has been working pretty well so far , but i have gotten to a point where i need to use the sdk for things like opening the invite modal and accessing the channel etc etc. 
 
Do you guys have any ideas on how i can fix the embedded sdk , or if there are docs on how to open the invite modal and access the current guild and channel ?

Thank you guys

Here is my current auth2 flow that works : 

```ts

    const LOGIN_URL = import.meta.env.VITE_LOGIN_URL; 
    const API_URL = import.meta.env.VITE_API_URL;
    onMount(async () => {
        user = localStorage.getItem('user');
        if (!user) {
            const code = new URLSearchParams(location.search).get('code');
            if (!code) {
                // redirect to login page
                console.log("Redirecting to login page "  + LOGIN_URL);
                window.location.href = LOGIN_URL;
                return;
            }
            console.log("Code: " + code);
            const res = await axios.post(API_URL + '/users/token', {
                code : code
            }).then(res => res.data).catch(()=>{
                window.location.href = LOGIN_URL;
            });

            // Save user to localStorage and store
            const newUser = res.user;
            localStorage.setItem('user', JSON.stringify(newUser));
            userStore.set(newUser);
        } else {
            const usr = JSON.parse(user);
            const res = await axios.get(API_URL + '/users/@me', {headers : {Authorization : `Bearer ${usr.access_token}`}} ).then(res => res.data);
            console.log(res.user);
            userStore.set(res.user);
        }
    });

```

**Comment by matthova** [comment]
Closing this for now but please reopen if the issue persists.
