### ISSUE TITLE
Joining Activity opens "First Use" Dialog twice

### ISSUE THREAD

**Issue by MaxDaten** [discord/embedded-app-sdk#245]
Hello,

since today the "First Use Dialog" seems to open twice when joining an existing activity. My user-journey test went red today. It uses Playwright to start an activity with user A and uses a different browser context to join the activity with user B.

While user A is presented the "first use dialog" once, user B is shown the dialog a second time after user B hits "Continue" on the first shown dialog.

See the short trimmed record for user B:
https://github.com/user-attachments/assets/d82e1d0e-9c17-49bd-96bd-3b8e73f15f57

Hope this is the right place for the report.

**Comment by donaldchen** [comment]
Thanks for the bug report! This should now be fixed on Discord desktop / web canary today and also on Discord Android / iOS app major app version 246
