### ISSUE TITLE
problem in documentation

### ISSUE THREAD

**Issue by DiogenesYazan** [discord/embedded-app-sdk#35]
there is a problem in the documentation when creating the clone, it is being used:

git clone git@github.com:discord/getting-started-activity.git

which presents an error, instead of:

git clone https://github.com/discord/getting-started-activity.git

I'm a beginner and I got a little stuck on this part.

**Comment by Malix-off** [comment]
Where?

**Comment by DiogenesYazan** [comment]
ah tks
