### ISSUE TITLE
error while install the package

### ISSUE THREAD

**Issue by LewdHuTao** [discord/embedded-app-sdk#37]
Hi, I think you guys forgot to change the version of the package while releasing this. Apparently when you try to install `@discord/embedded-app-sdk` you will get an error like this:

Update: pnpm does install the package fine but not npm

```bash
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:@discord/embedded-app-sdk@*
```

For anyone who gets this error, it can be easily fixed by changing the `@discord/embedded-app-sdk` version to '^1.0.0' in the `packages/client/package.json` file.

**Comment by Malix-off** [comment]
https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/package.json#L3

https://www.npmjs.com/package/@discord/embedded-app-sdk

**Comment by LewdHuTao** [comment]
> What was the command you typed?
> 
> https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/package.json#L3
> 
> https://www.npmjs.com/package/@discord/embedded-app-sdk?activeTab=versions

if you go to `examples/discord-activity-starter/packages/client/package.json` you can see that the package is not yet updated to version 1.0.0

https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/discord-activity-starter/packages/client/package.json#L10

**Comment by Miniontoby** [comment]
Same in the react-colyseus example!

https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/react-colyseus/packages/client/package.json#L11

However, when using pnpm it does install, tho... Only npm doesn't know what to do...

**Comment by Malix-off** [comment]
> However, when using pnpm it does install, tho... Only npm doesn't know what to do...

Aah!
That's why I didn't succeed to reproduce that issue

**Comment by LewdHuTao** [comment]
> Same in the react-colyseus example!
> 
> https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/react-colyseus/packages/client/package.json#L11
> 
> However, when using pnpm it does install, tho... Only npm doesn't know what to do...

Apparently all example folders will return the same error. I don't know if they should update the package version or let people use pnpm only.

https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/discord-activity-starter/packages/client/package.json#L10

https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/nested-messages/package.json#L14

https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/react-colyseus/packages/client/package.json#L11

https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/sdk-playground/packages/client/package.json#L17

**Comment by Miniontoby** [comment]
> > Same in the react-colyseus example!
> > https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/react-colyseus/packages/client/package.json#L11
> > 
> > However, when using pnpm it does install, tho... Only npm doesn't know what to do...
> 
> Apparently all example folders will return the same error. I don't know if they should update the package version or let people use pnpm only.
> 
> https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/discord-activity-starter/packages/client/package.json#L10
> 
> https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/nested-messages/package.json#L14
> 
> https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/react-colyseus/packages/client/package.json#L11
> 
> https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/sdk-playground/packages/client/package.json#L17

I updated my comment, cause apparently it was mentioned:

> These projects consume this repo's root `@discord/embedded-app-sdk` directly via [pnpm workspaces](https://pnpm.io/workspaces)

**Comment by DiogenesYazan** [comment]
This worked with me:

"@discord/embedded-app-sdk": "^1.0.0"

**Comment by LewdHuTao** [comment]
> I updated my comment
> > These projects consume this repo's root `@discord/embedded-app-sdk` directly via [pnpm workspaces](https://pnpm.io/workspaces)

It makes sense now why `npm` does not work

**Comment by gabemeola** [comment]
The examples in this repo use `pnpm` — you'll need to run `pnpm install` before running the activity-starter example.

Outside of this repo you can install `@discord/embedded-app-sdk` with whatever package manger you prefer.
