### ISSUE TITLE
[Problem] Install instructions react-colyseus example incomplete

### ISSUE THREAD

**Issue by Miniontoby** [discord/embedded-app-sdk#39]
# The problem

At the react-colyseus example the instructions are incomplete for installing

The current command shown is `pnpm install`:
https://github.com/discord/embedded-app-sdk/blob/5cc3da806a8bc35b3a3b3c289975c7f14e662591/examples/react-colyseus/README.md?plain=1#L47

This however shows this:
```
miniontoby:/opt/discordactivities/react-colyseus $ pnpm install
Already up to date
Done in 2.2s
miniontoby:/opt/discordactivities/react-colyseus $
```

As you can see, it didn't install anything. I then ran the dev command that was after the install step, and it didn't work, because it was missing node_modules folder.

# Solution making

Looking at the dev command, I can see that the command runs `pnpm run --filter \"./packages/**\" --parallel dev`

So I ran `pnpm install --filter "./packages/**"` and it installed the packages and after that the dev command also worked.

# Suggested next action

So either the package.json needs to be altered OR the instructions in the README need to be altered...

---

---

**Update 7-4-2024**:
Since Discord didn't reply, here are my instructions to fix the problem.

# My Solution

If you have moved the example out of the folder follow solution 1, else follow solution 2

## 1. If you have moved the example out of the folder

You just need to add an `pnpm-workspace.yaml` file in the folder and give it these contents:
```yaml
packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
```
Then `pnpm install` will work fine.

## 2. If you have it still in the examples folder

I would guess it would still install it, since it installs the whole workspace, but else make this change to `package.json`

```patch
diff --git a/examples/react-colyseus/package.json b/examples/react-colyseus/package.json
index 54431c0..42c6d77 100644
--- a/examples/react-colyseus/package.json
+++ b/examples/react-colyseus/package.json
@@ -5,7 +5,8 @@
   "description": "A starter project using react and colyseus",
   "main": "index.js",
   "scripts": {
+    "install": "pnpm install --filter \"./packages/**\"",
     "dev": "pnpm run --filter \"./packages/**\" --parallel dev",
     "tunnel": "cloudflared tunnel --url http://localhost:3000"
   },
   "author": "",
```
And run `pnpm run install` to install

## Extra fix for build command

Also the `package.json` is missing a `build` script, so here is a patch file to make that work
```patch
diff --git a/examples/react-colyseus/package.json b/examples/react-colyseus/package.json
index 54431c0..007c3dc 100644
--- a/examples/react-colyseus/package.json
+++ b/examples/react-colyseus/package.json
@@ -6,6 +6,7 @@
   "main": "index.js",
   "scripts": {
     "dev": "pnpm run --filter \"./packages/**\" --parallel dev",
+    "build": "pnpm run --filter \"./packages/**\" --parallel build",
     "tunnel": "cloudflared tunnel --url http://localhost:3000"
   },
   "author": "",
```

**Comment by matthova** [comment]
Great callout. The easiest solution, imo, could be to tell people to run `pnpm install` from the root of the repo. I've spun up a PR accordingly https://github.com/discord/embedded-app-sdk/pull/136.  

There is value in supporting pnpm install from inside the example directory instead, however, I think we'll sooner migrate all of the examples out of this repo than continue to support workspaces.

I really appreciate the attention to detail here and I even learned a bit about pnpm functionality 😅 so thank you for your thoughtful issue.
