### ISSUE TITLE
The client throws an error when response_type is token in command AUTHORIZE

### ISSUE THREAD

**Issue by kuylar** [discord/embedded-app-sdk#47]
First of all, I know that using `response_type: token` is not meant to be used in Embedded Apps. However, while writing an SDK wrapper for Godot, I decided to try sending it to check if it would work.

The API request succeeded, but I got this error as a response, instead of a normal error message telling me to use `response_type: code` instead (that's what I expected to get).

```json
{
    "code": 1000,
    "message": "Cannot read properties of undefined (reading 'split')"
}
```

After checking the API side, I found out that the response was successful, but my theory is that the client splits the response string by `?`, expecting the code to be in there, but since the token url data is in the hash instead of in the query, this throws an exception.

Would love to hear more about this. Thanks in advance!

**Comment by matthova** [comment]
Great callout. We do not support implicit flows for activities and will update the RPC server to notify users accordingly. I'll leave this issue open for now and hope to close it once a better error is surfaced.
