### ISSUE TITLE
[Suggestion] Automatically provide a valid access token without server exchange

### ISSUE THREAD

**Issue by maiconcarraro** [discord/embedded-app-sdk#48]
## Use case

The proposal in README already is "The Embedded App SDK handles the communication between Discord and your iframed application", expectations would be to allow developers to create solo **client side** apps **without** the need to spin up a server only to exchange the code<>token. 

As example, [Twitch extensions](https://dev.twitch.tv/docs/extensions/frontend-api-usage/) automatically generate a valid user access token once they accept to share the scope, this allows to skip the server and build fully **static** deployed apps while still making requests to the discord API from the client.

For specific cases where you need to fetch external data, do special validations, you could reuse the token like Twitch, check integrity (using secret id) and allow/deny actions. (This being an optional flow)

**Comment by matthova** [comment]
Thank you for the suggestion and use case explanation. While we'd love to support [implicit token grant flows](https://oauth.net/2/grant-types/implicit/) we don't have a solid path forward for them at the moment. There is a possibility to expand for this use case, but it's not something we're ready to support at this time.
