### ISSUE TITLE
[Bug] OAuth not working - invalid_request: Missing "redirect_uri" in request

### ISSUE THREAD

**Issue by Miniontoby** [discord/embedded-app-sdk#49]
Whilst running the `react-colyseus` example, after I authenticated I got this error:
```js
{
    "code": 5000,
    "message": "OAuth2 Error: invalid_request: Missing \"redirect_uri\" in request."
}
```

---

Update: I have fixed it by adding in any URL at the Redirects at the OAuth tab of the developers console.

**Comment by Miniontoby** [comment]
Update: I have fixed it by adding in any URL at the Redirects at the OAuth tab of the developers console.

**Comment by Histmy** [comment]
OMG, thank you so much for this question. I have been debugging this issue for several hours now without any luck. I think this should either be patched and not happen, or at least properly communicated in some documentation.

**Comment by exomlapi** [comment]
wow, thanks...
