### ISSUE TITLE
Support dynamic ports & proxy full range of ports for game servers

### ISSUE THREAD

**Issue by kdzapp** [discord/embedded-app-sdk#50]
Currently, when we connect to our individual game servers the ports being forwarded are only 80/442, but our game servers use dynamically assigned ports & are connected to directly by clients, and use ports outside of just 433/80. An example server we'd want to connect would be `wss://86d96a.edge.hathora.dev:51738/`. 

The URL mapping should support variables & also support proxying any port.
![image](https://github.com/discord/embedded-app-sdk/assets/14914386/d9f3fd45-e585-43a1-8dde-4de598b9f6d1)

**Comment by joeynenni** [comment]
I also filed an issue for this here: https://github.com/discord/embedded-app-sdk/issues/46

**Comment by devsnek** [comment]
closing in favor of 46
