### ISSUE TITLE
Tutorial not working, nothing happening after discordSdk.commands.authenticate()

### ISSUE THREAD

**Issue by GraceHopper0012** [discord/embedded-app-sdk#61]
Tried everything, using console.log() statements every few lines and breakpoints. Execution stops at
`auth = await discordSdk.commands.authenticate({
		access_token,
	});`

Just followed the tutorial at https://discord.com/developers/docs/activities/building-an-activity

No errors or anything, don't know what else to share, just lemme know what you need if you do need something else

**Comment by chadulous** [comment]
I keep getting "OAuth2 Error: invalid_request: Missing "redirect_uri" in request."

**Comment by chadulous** [comment]
This happens with my actual app, and when I clone the tutorial code

**Comment by SenaYora** [comment]
Be sure your client as a proxy in his `vite.config.js` : 
```js
export default defineConfig({
  envDir: '..',
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:3001',
      },
    },
  },
  // ...
});
```

Otherwise your client points by default to `${CLIENT_URL}/api/token`, but you want it to point to `${SERVER_URL}/api/token` which is `http://localhost:3001`

**Comment by GraceHopper0012** [comment]
Btw @chadulous, you might wanna take a look at [this](https://github.com/discord/embedded-app-sdk/issues/49#issuecomment-2012452715)

**Comment by RedHairring** [comment]
I am also having issues with the tutorial at https://discord.com/developers/docs/activities/building-an-activity. I'm unable to see any console.logs at all and cannot get past the part where you set the activity channel name. The app seems to run fine but console.logs never output in my terminal and the channel name does not show. I have zero errors as well.

**Comment by GraceHopper0012** [comment]
Yeah we had the same issue, seems like logs aren't logged before discordSdk.ready() which took forever in some cases. But I do not know, why

**Comment by GraceHopper0012** [comment]
# UPDATE:
Now working with new created app, no clue why not working first try, maybe some setting, therefore leaving the issue open. But might help someone with the same problem.

**Comment by GraceHopper0012** [comment]
Nope, just seems to be luck, some newly created applications work, some don't, no idea why

**Comment by JanakXD** [comment]
> I keep getting "OAuth2 Error: invalid_request: Missing "redirect_uri" in request."

make sure you follow this step : [OAuth2 redirect URI](https://discord.com/developers/docs/activities/building-an-activity#you-must-set-up-a-oauth2-redirect-uri-in-order-for-this-example-to-work)

**Comment by colinloretz** [comment]
As mentioned above, make sure you have _something_ set for your [OAuth2 redirect URI](https://discord.com/developers/docs/activities/building-an-activity#you-must-set-up-a-oauth2-redirect-uri-in-order-for-this-example-to-work).
