### ISSUE TITLE
patchUrlMappings does not support targets with parameter matched ports

### ISSUE THREAD

**Issue by joeynenni** [discord/embedded-app-sdk#64]
If issue https://github.com/discord/embedded-app-sdk/issues/46 is going to be fixed then the `patchUrlMappings` function should also support URL mappings with parameter matching for ports in the target.

The current implementation of `patchUrlMappings` produces the following result when a client app served from `1234.discordsays.com` tries making a request to `86d96a.edge.hathora.dev:51738` with a parameter matched port in the target:

```
patchUrlMappings([{ prefix: '/hathora/edge/{subdomain}/{port}', target: '{subdomain}.edge.hathora.dev:{port}' }])
```

Expected result: Client app makes a request to `1234.discordsays.com/hathora/edge/86d96a/51738` instead of `86d96a.edge.hathora.dev:51738`

Actual result: An error occurs on client app on load (`Uncaught TypeError: Failed to construct 'URL': Invalid URL at` [matchAndRewriteURL](https://github.com/discord/embedded-app-sdk/blob/main/src/utils/url.ts#L36))

This error occurs because the line at https://github.com/discord/embedded-app-sdk/blob/main/src/utils/url.ts#L36 attempts to construct a `new URL` with the target value. However, if the target value has a non-numeric port (like the parameter matched `:{port}` from the example) then the `URL` constructor will fail.

**Comment by matthova** [comment]
Great callout. Thanks for the minimal repro explanation. If we can resolve the known issue with the proxy we will absolutely make sure to update `patchUrlMappings` accordingly. I'm going to close this issue, but if additional issues related to port mapping or `patchUrlMappings` are found, please open another issue.
