### ISSUE TITLE
Vite/uuid incompatibility in `react-colyseus` example.

### ISSUE THREAD

**Issue by jclevine** [discord/embedded-app-sdk#70]
After running `pnpm install` (which seems to run correctly), when I try to `pnpm dev` I get the following 4 errors, all relating to `uuid`:
```
packages/client dev: Build failed with 4 errors:
packages/client dev: ../../../../node_modules/.pnpm/vite@2.9.16**/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:38597:7: 
ERROR: [plugin: vite:dep-scan] Missing "./dist/esm-browser/stringify.mjs" export in "uuid" package

packages/client dev: ../../../../node_modules/.pnpm/vite@2.9.16/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:38597:7: 
ERROR: [plugin: vite:dep-scan] Missing "./dist/esm-browser/v3.mjs" export in "uuid" package

packages/client dev: ../../../../node_modules/.pnpm/vite@2.9.16/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:38597:7: 
ERROR: [plugin: vite:dep-scan] Missing "./dist/esm-browser/v4.mjs" export in "uuid" package

packages/client dev: ../../../../node_modules/.pnpm/vite@2.9.16/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:38597:7: 
ERROR: [plugin: vite:dep-scan] Missing "./dist/esm-browser/v5.mjs" export in "uuid" package
```

I should mention that I am running this on a Windows 11 machine, using IntelliJ IDEA.

**Comment by Snowy7** [comment]
Same here.

**Comment by jclevine** [comment]
@Snowy7 Are you also doing this on a Windows 11 machine or otherwise?

**Comment by Miniontoby** [comment]
The `pnpm install` command doesn't work from the root of the example!

See #39 for more information.

You need to go into the `packages/client/` and run `pnpm install` there and to `packages/server` and run `pnpm install`  OR use my suggested change seen in my issue.

**Comment by matthova** [comment]
This should be resolved by running `pnpm install` from the root of `embedded-app-sdk`. I've [updated the readme](https://github.com/discord/embedded-app-sdk/tree/main/examples/react-colyseus#running-your-app-locally) accordingly.

Please reopen this issue if the problem persists after running `pnpm install` from the root of `embedded-app-sdk`

**Comment by terryds** [comment]
I get the same issue in "discord-activity-starter" example

![image](https://github.com/discord/embedded-app-sdk/assets/11571395/2ae18c75-55eb-4d72-8d2a-e5bcff32dc1c)

**Comment by JustinBeckwith** [comment]
@terryds are you running `pnpm install` from the root of the directory?

**Comment by terryds** [comment]
yes, from the root directory

after i find it not working, i also tried to run pnpm install on both
server & client dir

**Comment by JustinBeckwith** [comment]
I just tried this, and it works for me:

```
$ cd into/repository/root
$ node --version # make sure it's 20 or up
$ pnpm --version $ make sure it's 8.x
$ rm -rf **/node_modules # let's start over with installation
$ pnpm install
$ cd examples/react-colyseus
$ pnpm dev
```

If you follow those steps, does it work?
