### ISSUE TITLE
Export types

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [discord/embedded-app-sdk#71]
I'm using this in a typescript project, it would be nice to be able to type the variables based on the SDK. Right now, I can supplement it by copying the return type from the `.d.ts`.

This is the svelte code I'm using to get started:
```svelte
<script lang='ts'>
    import { setupDiscordSdk, type DiscordAuthResponse } from "$lib/discord";
    import { onMount } from "svelte";

    let authInfo: DiscordAuthResponse | undefined;

    onMount(async () => {
        const auth = await setupDiscordSdk();
        authInfo = auth;
    })
</script>

{authInfo ? authInfo.user : ''}

<canvas></canvas>
```
And here's the relevant part of the `setupDiscordSdk` function.
```ts
return await discordSdk.commands.authenticate({
    access_token
});
```
```ts
export type DiscordAuthResponse = {
    access_token: string;
    user: {
        username: string;
        discriminator: string;
        id: string;
        public_flags: number;
        avatar?: string | null | undefined;
        global_name?: string | null | undefined;
    };
    scopes: (...)[];
    expires: string;
    application: {
        id: string;
        description: string;
        name: string;
        icon?: string | null | undefined;
        rpc_origins?: string[] | undefined;
    };
}
```

I would appreciate it very much. I personally don't have time to make a pr this week, but I'll have enough time next week if I remember.

**Comment by Daikonnbatake** [comment]
I think it's a very good idea!

**Comment by RihanArfan** [comment]
I'm implementing this within a Nuxt (Vue.js) application and here's what I've done to automatically infer types until they're exported by the SDK.

```ts
// composables/discord.ts

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

type DiscordAuth = AsyncReturnType<typeof discordSdk.commands.authenticate>;

export const useDiscordAuth = () => {
  return useState<DiscordAuth | null>("discord-auth", () => null);
};
```

![image](https://github.com/discord/embedded-app-sdk/assets/20425781/95768c08-c276-45e0-934e-516e873c967c)

**Comment by matthova** [comment]
@TheBlueOompaLoompa great callout. We'll see if we can export these return types for consumption.

In the meantime, depending on your typescript version, you can use `Awaited` and `ReturnType`

```ts
type Auth = Awaited<ReturnType<typeof discordSdk.commands.authenticate>>;
```

I hope to add command return types soon. We'll make an announcement over in the Discord Developers server https://discord.gg/discord-developers when new releases are available.
